version: '3.9'

services:
  postgres:
    container_name: postgres-sindMeet
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres-sindMeet
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
